// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/toms/less/protos/runtime.proto

package com.toms.less.server;

public interface ResponseDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.ResponseData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; headers = 1;</code>
   */
  int getHeadersCount();
  /**
   * <code>map&lt;string, string&gt; headers = 1;</code>
   */
  boolean containsHeaders(
      java.lang.String key);
  /**
   * Use {@link #getHeadersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getHeaders();
  /**
   * <code>map&lt;string, string&gt; headers = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getHeadersMap();
  /**
   * <code>map&lt;string, string&gt; headers = 1;</code>
   */

  java.lang.String getHeadersOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; headers = 1;</code>
   */

  java.lang.String getHeadersOrThrow(
      java.lang.String key);

  /**
   * <code>.google.protobuf.Any body = 2;</code>
   * @return Whether the body field is set.
   */
  boolean hasBody();
  /**
   * <code>.google.protobuf.Any body = 2;</code>
   * @return The body.
   */
  com.google.protobuf.Any getBody();
  /**
   * <code>.google.protobuf.Any body = 2;</code>
   */
  com.google.protobuf.AnyOrBuilder getBodyOrBuilder();
}
