// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/toms/less/protos/runtime.proto

package com.toms.less.server;

public interface RuntimeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.RuntimeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string function = 2;</code>
   * @return The function.
   */
  java.lang.String getFunction();
  /**
   * <code>string function = 2;</code>
   * @return The bytes for function.
   */
  com.google.protobuf.ByteString
      getFunctionBytes();

  /**
   * <code>string version = 3;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 3;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string group = 4;</code>
   * @return The group.
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 4;</code>
   * @return The bytes for group.
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>string unit = 5;</code>
   * @return The unit.
   */
  java.lang.String getUnit();
  /**
   * <code>string unit = 5;</code>
   * @return The bytes for unit.
   */
  com.google.protobuf.ByteString
      getUnitBytes();

  /**
   * <code>string runtime = 6;</code>
   * @return The runtime.
   */
  java.lang.String getRuntime();
  /**
   * <code>string runtime = 6;</code>
   * @return The bytes for runtime.
   */
  com.google.protobuf.ByteString
      getRuntimeBytes();

  /**
   * <code>string status_msg = 7;</code>
   * @return The statusMsg.
   */
  java.lang.String getStatusMsg();
  /**
   * <code>string status_msg = 7;</code>
   * @return The bytes for statusMsg.
   */
  com.google.protobuf.ByteString
      getStatusMsgBytes();

  /**
   * <code>.server.ResponseData data = 8;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.server.ResponseData data = 8;</code>
   * @return The data.
   */
  com.toms.less.server.ResponseData getData();
  /**
   * <code>.server.ResponseData data = 8;</code>
   */
  com.toms.less.server.ResponseDataOrBuilder getDataOrBuilder();
}
