// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/toms/less/protos/runtime.proto

package com.toms.less.server;

public final class RuntimeProto {
  private RuntimeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_RuntimeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_RuntimeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_RuntimeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_RuntimeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_RequestData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_RequestData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_RequestData_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_RequestData_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_RequestData_ParametersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_RequestData_ParametersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_ResponseData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_ResponseData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_ResponseData_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_ResponseData_HeadersEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0src/main/java/com/toms/less/protos/run" +
      "time.proto\022\006server\032\031google/protobuf/any." +
      "proto\"\352\001\n\016RuntimeRequest\022\n\n\002id\030\001 \001(\t\022\020\n\010" +
      "function\030\002 \001(\t\022\017\n\007version\030\003 \001(\t\022\r\n\005group" +
      "\030\004 \001(\t\022\014\n\004unit\030\005 \001(\t\022\017\n\007timeout\030\006 \001(\003\022!\n" +
      "\004data\030\007 \001(\0132\023.server.RequestData\"*\n\007trig" +
      "ger\022\013\n\007UNKNOWN\020\000\022\010\n\004HTTP\020\001\022\010\n\004BASE\020\002\",\n\014" +
      "content_type\022\010\n\004TEXT\020\000\022\010\n\004JSON\020\001\022\010\n\004HTML" +
      "\020\002\"\352\001\n\017RuntimeResponse\022\n\n\002id\030\001 \001(\t\022\020\n\010fu" +
      "nction\030\002 \001(\t\022\017\n\007version\030\003 \001(\t\022\r\n\005group\030\004" +
      " \001(\t\022\014\n\004unit\030\005 \001(\t\022\017\n\007runtime\030\006 \001(\t\022\022\n\ns" +
      "tatus_msg\030\007 \001(\t\022\"\n\004data\030\010 \001(\0132\024.server.R" +
      "esponseData\"B\n\006status\022\013\n\007UNKNOWN\020\000\022\013\n\007SU" +
      "CCESS\020\001\022\013\n\007TIMEOUT\020\002\022\021\n\rEXECUTE_ERROR\020\003\"" +
      "\247\002\n\013RequestData\0221\n\007headers\030\001 \003(\0132 .serve" +
      "r.RequestData.HeadersEntry\0227\n\nparameters" +
      "\030\002 \003(\0132#.server.RequestData.ParametersEn" +
      "try\022\"\n\004body\030\003 \001(\0132\024.google.protobuf.Any\032" +
      ".\n\014HeadersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t:\0028\001\0321\n\017ParametersEntry\022\013\n\003key\030\001 \001(\t\022" +
      "\r\n\005value\030\002 \001(\t:\0028\001\"%\n\006method\022\010\n\004BASE\020\000\022\010" +
      "\n\004POST\020\001\022\007\n\003GET\020\002\"\226\001\n\014ResponseData\0222\n\007he" +
      "aders\030\001 \003(\0132!.server.ResponseData.Header" +
      "sEntry\022\"\n\004body\030\002 \001(\0132\024.google.protobuf.A" +
      "ny\032.\n\014HeadersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\t:\0028\0012I\n\016RuntimeService\0227\n\004Call\022\026.s" +
      "erver.RuntimeRequest\032\027.server.RuntimeRes" +
      "ponseB,\n\024com.toms.less.serverB\014RuntimePr" +
      "otoP\001\242\002\003RTGb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_server_RuntimeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_RuntimeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_RuntimeRequest_descriptor,
        new java.lang.String[] { "Id", "Function", "Version", "Group", "Unit", "Timeout", "Data", });
    internal_static_server_RuntimeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_server_RuntimeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_RuntimeResponse_descriptor,
        new java.lang.String[] { "Id", "Function", "Version", "Group", "Unit", "Runtime", "StatusMsg", "Data", });
    internal_static_server_RequestData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_server_RequestData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_RequestData_descriptor,
        new java.lang.String[] { "Headers", "Parameters", "Body", });
    internal_static_server_RequestData_HeadersEntry_descriptor =
      internal_static_server_RequestData_descriptor.getNestedTypes().get(0);
    internal_static_server_RequestData_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_RequestData_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_server_RequestData_ParametersEntry_descriptor =
      internal_static_server_RequestData_descriptor.getNestedTypes().get(1);
    internal_static_server_RequestData_ParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_RequestData_ParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_server_ResponseData_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_server_ResponseData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_ResponseData_descriptor,
        new java.lang.String[] { "Headers", "Body", });
    internal_static_server_ResponseData_HeadersEntry_descriptor =
      internal_static_server_ResponseData_descriptor.getNestedTypes().get(0);
    internal_static_server_ResponseData_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_ResponseData_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
