// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/toms/less/protos/runtime.proto

package com.toms.less.server;

public interface RuntimeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.RuntimeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string function = 2;</code>
   * @return The function.
   */
  java.lang.String getFunction();
  /**
   * <code>string function = 2;</code>
   * @return The bytes for function.
   */
  com.google.protobuf.ByteString
      getFunctionBytes();

  /**
   * <code>string version = 3;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 3;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string group = 4;</code>
   * @return The group.
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 4;</code>
   * @return The bytes for group.
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>string unit = 5;</code>
   * @return The unit.
   */
  java.lang.String getUnit();
  /**
   * <code>string unit = 5;</code>
   * @return The bytes for unit.
   */
  com.google.protobuf.ByteString
      getUnitBytes();

  /**
   * <code>int64 timeout = 6;</code>
   * @return The timeout.
   */
  long getTimeout();

  /**
   * <code>.server.RequestData data = 7;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.server.RequestData data = 7;</code>
   * @return The data.
   */
  com.toms.less.server.RequestData getData();
  /**
   * <code>.server.RequestData data = 7;</code>
   */
  com.toms.less.server.RequestDataOrBuilder getDataOrBuilder();
}
